# Sentinel配置

# 基础配置
port 26379
daemonize no
protected-mode no
dir /tmp

# 日志配置
loglevel notice
logfile ""

# 监控配置
sentinel monitor mymaster redis-master 6379 2
sentinel auth-pass mymaster 123456

# 故障转移配置
sentinel down-after-milliseconds mymaster 30000
sentinel failover-timeout mymaster 180000
sentinel parallel-syncs mymaster 1

# 客户端配置
sentinel deny-scripts-reconfig yes
sentinel resolve-hostnames no
announce-hostnames no